project:
  type: website

execute:
  freeze: auto

website:
  title: "Andrew Weatherman"
  favicon: images/favicon.png
  site-url: https://www.quantumjitter.com
  description: "A blog for gt and ggplot code in R {{< fa regular heart >}}"
  twitter-card: true
  open-graph: true
  navbar:
    title: Andrew Weatherman
    right:
      - text: R Resources
        href: r-resources/index.qmd
      - text: Code
        menu:
          - text: Visualizations
            href: viz/index.qmd
          - text: Other Stuff
            href: other-code/index.qmd
          - text: gt Theme Gallery
            href: gt-theme-gallery/index.qmd
      - text: My Work
        menu:
          - text: cbbdata
            url: https://cbbdata.aweatherman.com
          - text: cbbplotR
            url: https://cbbplotr.aweatherman.com
      - text: Music
        href: spotify/index.qmd
      - text: About
        href: https://www.aweatherman.com/
      - icon: twitter
        href: https://twitter.com/andreweatherman
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/andreweatherman/viz-site
          - text: Report a Bug
            url:  https://github.com/andreweatherman/viz-site/issues
  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) v<?quarto.version?>"
    right: "[@andreweatherman on Twitter](https://twitter.com/andreweatherman) || Template by Carl Goodwin"

format:
  html:
    theme:
      light: [flatly, scss/light.scss]
      dark: [darkly, scss/dark.scss]
    css: scss/styles.css
    code-link: true
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: kable
    comments:
      giscus:
        repo: andreweatherman/viz-site
        category: "Comments"
        mapping: "pathname"
        reactions-enabled: true
        loading: lazy
        input-position: "bottom"
        theme:
          light: light_high_contrast
          dark: dark_dimmed

editor: visual

filters:
  - quarto-version.lua

