project:
  type: website
  resources: project/wood/appfiles/

execute:
  freeze: auto

website:
  title: "Quantum Jitter"
  favicon: images/logo-grey.png
  site-url: https://www.quantumjitter.com
  description: "A data science and machine learning blog with the tidyverse at its {{< fa regular heart >}}"
  twitter-card: true
  open-graph: true
  navbar:
    logo: images/logo-light.png
    title: false
    right:
      - text: Projects
        href: project/index.qmd
      - text: Toolbox
        href: project/box/index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: About
        href: about/index.qmd
      - icon: rss
        href: project/index-R.xml
      - icon: github
        href: https://github.com/cgoo4/quantumjitter
  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) v<?quarto.version?> | Hosted by [{{< iconify simple-icons netlify >}}](https://www.netlify.com)"
    right: "© 2022 [Carl Goodwin](/about) | License [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)"

format:
  html:
    theme:
      light: [flatly, scss/light.scss]
      dark: [darkly, scss/dark.scss]
    code-link: true
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: kable
    comments:
      giscus:
        repo: cgoo4/quantumjitter
        category: "Comments"
        mapping: "pathname"
        reactions-enabled: true
        loading: lazy
        input-position: "bottom"
        theme: "transparent_dark"

editor: visual

filters:
  - quarto-version.lua

